export const TIMELINE_CONFIG = {
  START_HOUR: 11,
  END_HOUR: 24,
  SLOT_MINUTES: 15,
  DEFAULT_DURATION_MINUTES: 90,
  MIN_DURATION_MINUTES: 30,
  MAX_DURATION_MINUTES: 240,
  CELL_WIDTH_PX: 60,
  ROW_HEIGHT_PX: 60,
} as const;

export const RESERVATION_STATUS_COLORS: Record<string, string> = {
  PENDING: '#FCD34D',
  CONFIRMED: '#3B82F6',
  SEATED: '#10B981',
  FINISHED: '#9CA3AF',
  NO_SHOW: '#EF4444',
  CANCELLED: '#9CA3AF',
};

export const ZOOM_LEVELS = [50, 75, 100, 125, 150] as const;

